{% set setup_data = load_setup_py_data() %}
package:
  name: x-filter
  version: {{ setup_data['version'] }}

source:
  git_rev: {{ setup_data['version'] }}
  git_url: https://github.com/genomewalker/x-filter.git

build:
  number: 0
  skip: true  # [win and py27 or win32]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python>=3.7
    - setuptools
    - pip
    - Cython>=0.29.24
  run:
    - python>=3.7
    - pandas>=1.3.3
    - scipy>=1.5.2
    - tqdm==4.50.0
    - pysam>=0.17.0
    - numpy>=1.21.2
    - Cython>=0.29.24
    - pyranges>=0.0.112
    
test:
  commands:
    - xFilter -h

about:
  home: https://github.com/genomewalker/x-filter
  summary: "A simple tool to identify and clean misassemblies for ancient metagenomics"
  license: {{ setup_data['license'] }}
  license_file: LICENSE
